### DISCUSSION TITLE
Adopt commit standard to enable auto-labeling and changelog generation

### DISCUSSION THREAD

**Discussion by faustbrian** [ethereumjs/ethereumjs-monorepo#2112] [Ideas]
Pull requests always get manually labelled but if something like https://www.conventionalcommits.org/en/v1.0.0/ would be adopted you could automatically label pull requests via a GitHub workflow and could use https://github.com/git-chglog/git-chglog or alike to automatically generate changelogs. It would also make it easier and more obvious for contributors to know how pull request titles should be formatted.

```yaml
version: 1

labels:
  - label: "type: bugfix"
    title: "^fix.*"
  - label: "type: feature"
    title: "^feat.*"
  - label: "type: build"
    title: "^build.*"
  - label: "type: chore"
    title: "^chore.*"
  - label: "type: ci"
    title: "^ci.*"
  - label: "type: docs"
    title: "^docs.*"
  - label: "type: style"
    title: "^style.*"
  - label: "type: refactor"
    title: "^refactor.*"
  - label: "type: performance"
    title: "^perf.*"
  - label: "type: test"
    title: "^test.*"
```
